### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by qiuquanwu** [yangfuhe/node-wxpay#2]

**Comment by qiuquanwu** [comment]
yarn add v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@cloudbase/node-sdk > ts-node@8.10.2" has unmet peer dependency "typescript@>=2.7".
[4/4] Building fresh packages...
error E:\workspace\cxlai-api\functions\renewal\node_modules\node-aes-gcm: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: E:\workspace\cxlai-api\functions\renewal\node_modules\node-aes-gcm
Output:
E:\workspace\cxlai-api\functions\renewal\node_modules\node-aes-gcm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.5 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp http GET https://nodejs.org/download/release/v14.17.5/node-v14.17.5-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.17.5/node-v14.17.5-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.17.5/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.17.5/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v14.17.5/win-arm64/node.lib
gyp http GET https://nodejs.org/download/release/v14.17.5/win-x86/node.lib
gyp http 404 https://nodejs.org/download/release/v14.17.5/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.17.5/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v14.17.5/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v14.17.5/SHASUMS256.txt
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:397:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\workspace\cxlai-api\functions\renewal\node_modules\node-aes-gcm
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
